#############################################################################
# Makefile for building: raft-p2p
# Generated by qmake (2.01a) (Qt 4.8.7) on: Tue Nov 20 23:34:08 2018
# Project:  raft-p2p.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile raft-p2p.pro
#############################################################################
####### Compiler, tools and options
CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
####### Output directory
OBJECTS_DIR   = ./
####### Files
SOURCES       = main.cc moc_main.cpp
OBJECTS       = main.o \
        moc_main.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
        /usr/share/qt4/mkspecs/common/linux.conf \
        /usr/share/qt4/mkspecs/common/gcc-base.conf \
        /usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
        /usr/share/qt4/mkspecs/common/g++-base.conf \
        /usr/share/qt4/mkspecs/common/g++-unix.conf \
        /usr/share/qt4/mkspecs/qconfig.pri \
        /usr/share/qt4/mkspecs/features/qt_functions.prf \
        /usr/share/qt4/mkspecs/features/qt_config.prf \
        /usr/share/qt4/mkspecs/features/exclusive_builds.prf \
        /usr/share/qt4/mkspecs/features/default_pre.prf \
        /usr/share/qt4/mkspecs/features/release.prf \
        /usr/share/qt4/mkspecs/features/default_post.prf \
        /usr/share/qt4/mkspecs/features/shared.prf \
        /usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
        /usr/share/qt4/mkspecs/features/warn_on.prf \
        /usr/share/qt4/mkspecs/features/qt.prf \
        /usr/share/qt4/mkspecs/features/unix/thread.prf \
        /usr/share/qt4/mkspecs/features/moc.prf \
        /usr/share/qt4/mkspecs/features/resources.prf \
        /usr/share/qt4/mkspecs/features/uic.prf \
        /usr/share/qt4/mkspecs/features/yacc.prf \
        /usr/share/qt4/mkspecs/features/lex.prf \
        /usr/share/qt4/mkspecs/features/include_source_dir.prf \
        raft-p2p.pro
QMAKE_TARGET  = raft-p2p
DESTDIR       = 
TARGET        = raft-p2p
first: all
####### Implicit rules
.SUFFIXES: .o .c .cpp .cc .cxx .C
.cpp.o:
    $(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"
.cc.o:
    $(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"
.cxx.o:
    $(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"
.C.o:
    $(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"
.c.o:
    $(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"
####### Build rules
all: Makefile $(TARGET)
$(TARGET):  $(OBJECTS)  
    $(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
Makefile: raft-p2p.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
        /usr/share/qt4/mkspecs/common/linux.conf \
        /usr/share/qt4/mkspecs/common/gcc-base.conf \
        /usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
        /usr/share/qt4/mkspecs/common/g++-base.conf \
        /usr/share/qt4/mkspecs/common/g++-unix.conf \
        /usr/share/qt4/mkspecs/qconfig.pri \
        /usr/share/qt4/mkspecs/features/qt_functions.prf \
        /usr/share/qt4/mkspecs/features/qt_config.prf \
        /usr/share/qt4/mkspecs/features/exclusive_builds.prf \
        /usr/share/qt4/mkspecs/features/default_pre.prf \
        /usr/share/qt4/mkspecs/features/release.prf \
        /usr/share/qt4/mkspecs/features/default_post.prf \
        /usr/share/qt4/mkspecs/features/shared.prf \
        /usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
        /usr/share/qt4/mkspecs/features/warn_on.prf \
        /usr/share/qt4/mkspecs/features/qt.prf \
        /usr/share/qt4/mkspecs/features/unix/thread.prf \
        /usr/share/qt4/mkspecs/features/moc.prf \
        /usr/share/qt4/mkspecs/features/resources.prf \
        /usr/share/qt4/mkspecs/features/uic.prf \
        /usr/share/qt4/mkspecs/features/yacc.prf \
        /usr/share/qt4/mkspecs/features/lex.prf \
        /usr/share/qt4/mkspecs/features/include_source_dir.prf \
        /usr/lib/x86_64-linux-gnu/libQtGui.prl \
        /usr/lib/x86_64-linux-gnu/libQtNetwork.prl \
        /usr/lib/x86_64-linux-gnu/libQtCore.prl
    $(QMAKE) -o Makefile raft-p2p.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtNetwork.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
    @$(QMAKE) -o Makefile raft-p2p.pro
dist: 
    @$(CHK_DIR_EXISTS) .tmp/raft-p2p1.0.0 || $(MKDIR) .tmp/raft-p2p1.0.0 
    $(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/raft-p2p1.0.0/ && $(COPY_FILE) --parents main.hh .tmp/raft-p2p1.0.0/ && $(COPY_FILE) --parents main.cc .tmp/raft-p2p1.0.0/ && (cd `dirname .tmp/raft-p2p1.0.0` && $(TAR) raft-p2p1.0.0.tar raft-p2p1.0.0 && $(COMPRESS) raft-p2p1.0.0.tar) && $(MOVE) `dirname .tmp/raft-p2p1.0.0`/raft-p2p1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/raft-p2p1.0.0
clean:compiler_clean 
    -$(DEL_FILE) $(OBJECTS)
    -$(DEL_FILE) *~ core *.core
####### Sub-libraries
distclean: clean
    -$(DEL_FILE) $(TARGET) 
    -$(DEL_FILE) Makefile
check: first
mocclean: compiler_moc_header_clean compiler_moc_source_clean
mocables: compiler_moc_header_make_all compiler_moc_source_make_all
compiler_moc_header_make_all: moc_main.cpp
compiler_moc_header_clean:
    -$(DEL_FILE) moc_main.cpp
moc_main.cpp: main.hh
    /usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) main.hh -o moc_main.cpp
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
    -$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 
####### Compile
main.o: main.cc main.hh
    $(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cc
moc_main.o: moc_main.cpp 
    $(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_main.o moc_main.cpp
####### Install
install:   FORCE
uninstall:   FORCE
FORCE:


cmake_minimum_required(VERSION 3.12)
project(raft-p2p)
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_AUTOMOC ON)
find_package( Qt5Core REQUIRED )
find_package( Qt5Widgets REQUIRED )
find_package( Qt5Gui REQUIRED )
include_directories(.)
add_executable(raft-p2p
        main.cc
        main.hh
        raft-p2p.pro)
qt5_use_modules( raft-p2p Core Widgets Gui Network)